export default [
  {
    id: "1",
    cookieName: "ABCD",
    domain: "example.com",
    path: "example/home/about",
    expireDate: "2023/10/01",
    category: "",
  },
  {
    id: "2",
    cookieName: "ABCD",
    domain: "example.com",
    path: "example/home/about",
    expireDate: "2023/10/01",
    category: "",
  },
  {
    id: "3",
    cookieName: "ABCD",
    domain: "example.com",
    path: "example/home/about",
    expireDate: "2023/10/01",
    category: "",
  },
  {
    id: "4",
    cookieName: "ABCD",
    domain: "example.com",
    path: "example/home/about",
    expireDate: "2023/10/01",
    category: "",
  },
  {
    id: "5",
    cookieName: "ABCD",
    domain: "example.com",
    path: "example/home/about",
    expireDate: "2023/10/01",
    category: "",
  },
];
